### ISSUE TITLE
about startTracking

### ISSUE THREAD

**Issue by crazypoo** [lukevanin/autonomous-robot#1]
Hola,amigo.Function startTracking() have some problem.
2021-06-05 01:34:41.371465+0800 AutonomousRobot[3402:790289] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Scene Reconstruction type not supported by this configuration'
*** First throw call stack:
(0x191a1025c 0x1a5d21480 0x1bba37ca8 0x10257b424 0x102579c28 0x10257b910 0x193beb394 0x193bef94c 0x193befd2c 0x1942f2d04 0x1942f2518 0x1942f33ac 0x1da7eb2f4 0x194303f6c 0x1025397d8 0x102539998 0x1942b17b0 0x1942b3150 0x1942b8f24 0x19398b8b0 0x193eb02c8 0x19398c398 0x19398bea0 0x19398c1c4 0x19398ba80 0x19399371c 0x193dca38c 0x193ec8184 0x193993410 0x1937d2ad4 0x1937d1580 0x1937d2720 0x1942b70fc 0x193df0a84 0x1a0a22d00 0x1a0a4a4fc 0x1a0a30420 0x1a0a4a214 0x102e4d32c 0x102e507e4 0x1a0a6ee04 0x1a0a6eacc 0x1a0a6efa0 0x19198f8a8 0x19198f7a8 0x19198eafc 0x191989018 0x1919887d0 0x1a86c8570 0x1942b52d0 0x1942ba84c 0x1a505d87c 0x102539ca8 0x102539c20 0x102539d70 0x191667140)
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Scene Reconstruction type not supported by this configuration'
terminating with uncaught exception of type NSException

**Comment by lukevanin** [comment]
> Scene Reconstruction type not supported by this configuration'

This usually means that you are trying to use mesh reconstruction on a device that does not have LiDAR.

According to the documentation: 

> Scene reconstruction requires a device with a LiDAR Scanner, such as the fourth-generation iPad Pro.

https://developer.apple.com/documentation/arkit/arworldtrackingconfiguration/3521377-supportsscenereconstruction

There is unfortunately nothing that can be done from the app if the hardware does not support scene reconstruction.

**Comment by crazypoo** [comment]
oh,that you can use  iPad(x,x) fuction in you project to check developer use any device
